version: '3.8'

volumes:
  mysql:

services:
  mysql:
    image: mysql:8.0.22
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exadel_internships
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  spring-backend:
    image: backend-keycloak:3.0
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/exadel_internships?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql
      - keycloak

  keycloak:
    image: jboss/keycloak:12.0.4
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: exadel_internships
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: valik
      KEYCLOAK_PASSWORD: exadel
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/providers/username-90.jar:/opt/jboss/keycloak/standalone/deployments/username-90.jar:z
    depends_on:
      - mysql