version: '3.8'
services:
  mysql-standalone:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=exadel_internships
      - MYSQL_PASSWORD=root
    ports:
      - "3307:3306"
  spring-backend:
    image: backend-team1:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/exadel_internships?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone