package com.exadel.project.trainee.entity;

public enum TraineeStatus {
    REGISTERED,
    RECRUITER_INTERVIEW_PENDING,
    RECRUITER_INTERVIEW_REJECTED,
    RECRUITER_INTERVIEW_ACCEPTED,
    RECRUITER_INTERVIEW_PASSED,
    TECHNICAL_INTERVIEW_PENDING,
    TECHNICAL_INTERVIEW_REJECTED,
    TECHNICAL_INTERVIEW_ACCEPTED,
    REJECTED,
    ACCEPTED
}